### ISSUE TITLE
ERRO   Terminating due to error error:open client.pem: no such file or directory utils/bail.go:12 [ Teleport Jira ]

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#108]
I've been trying to test Jira Server now I'm back but I'm running into this issue 

```
teleport5auth ~: sudo teleport-jira start -d
DEBU   DEBUG logging enabled logrus/exported.go:117
INFO   Starting Teleport Access JIRAbot 0.1.0-alpha.3:teleport-jira-v0.1.0-alpha.3-0-gea1ef8e jira/app.go:74
ERRO   Terminating due to error error:open client.pem: no such file or directory utils/bail.go:12
DEBU   "\nERROR REPORT:\nOriginal Error: *os.PathError open client.pem: no such file or directory\nStack Trace:\n\t/go/src/github.com/gravitational/teleport-plugins/access/tls.go:44 github.com/gravitational/teleport-plugins/access.LoadX509Cert\n\t/go/src/github.com/gravitational/teleport-plugins/access/tls.go:17 github.com/gravitational/teleport-plugins/access.LoadTLSConfig\n\t/go/src/github.com/gravitational/teleport-plugins/access/jira/app.go:87 main.(*App).run\n\t/go/src/github.com/gravitational/teleport-plugins/utils/process.go:208 github.com/gravitational/teleport-plugins/utils.NewServiceJob.func1\n\t/go/src/github.com/gravitational/teleport-plugins/utils/process.go:229 github.com/gravitational/teleport-plugins/utils.(*serviceJob).DoJob\n\t/go/src/github.com/gravitational/teleport-plugins/utils/process.go:82 github.com/gravitational/teleport-plugins/utils.NewProcess.func2.1\n\t/usr/local/go/src/runtime/asm_amd64.s:1358 runtime.goexit\nUser Message: \n" utils/bail.go:12
```

I know my cert / pem / crt as I'm using the same for Mattermost.

**Comment by xnutsive** [comment]
Can you please paste the teleport-jira config, and ls in the current directory, path to dir with certificates? I'll look into it.

**Comment by benarent** [comment]
I've tried a bunch of different ports, it seems different than mattermost / slack. I thought it could be due to having TLS not correctly setup on Jira but that's fixed now. 

```toml
# example jira plugin configuration TOML file
[teleport]
# Server GRPC API address
#ort GRPC client certificate
auth-server = "teleport-ent-4-3.practice.io:3025"  # Teleport Auth Server GRPC API address
client-key = "/auth.key" # Teleport GRPC client secret key
client-crt = "/auth.crt" # Teleport GRPC client certificate
root-cas = "/auth.cas"   # Teleport cluster CA certs

[jira]
url = "https://jira.practice.io/jira"    # JIRA URL. For JIRA Cloud, https://[my-jira].atlassian.net
username = "teleport-jira"        # JIRA username
api_token = "2?KVXXX"                 # JIRA API Basic Auth token
project = "TEL1"                  # JIRA Project key

[http]
# listen_addr = ":8081" # Network address in format [addr]:port on which webhook server listens, e.g. 0.0.0.0:443
# public_addr = "example.com" # URL on which webhook server is accessible externally, e.g. [https://]teleport-jira.example.com
listen_addr = ":8081"
public_addr = "teleport-ent-4-3.practice.io"
# The below host was used for mattermost
#host = "teleport-ent-4-3.practice.io:8081"
#https_key_file = "/var/lib/teleport/plugins/jira/server.key"  # TLS private key
#https_cert_file = "/var/lib/teleport/plugins/jira/server.crt" # TLS certificate
https-key-file = "/var/lib/teleport/webproxy_key.key"  # TLS private key
https-cert-file = "/var/lib/teleport/webproxy_cert.crt" # TLS certificate

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/jira.log"
severity = "DEBUG" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```
