### ISSUE TITLE
[Slack Plugin] Failed to find roles or traits in x509

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport-plugins#230]
I've followed the docs and configured my Slack plugin like so:

User and role:

```yaml
kind: user
metadata:
  name: access-plugin
spec:
  roles: ['access-plugin']
version: v2
---
kind: role
metadata:
  name: access-plugin
spec:
  allow:
    rules:
      - resources: ['access_request']
        verbs: ['list', 'read']
      - resources: ['access_plugin_data']
        verbs: ['update']
    # teleport currently refuses to issue certs for a user with 0 logins,
    # this restriction may be lifted in future versions.
    logins: ['access-plugin']
```

My `teleport-slack.toml`:
```
# example slack plugin configuration TOML file

[teleport]
auth_server = "slack.go-teleport.com:3025"           # Teleport Auth Server GRPC API address
client_key = "/var/lib/teleport/plugins/slack/auth.key" # Teleport GRPC client secret key
client_crt = "/var/lib/teleport/plugins/slack/auth.crt" # Teleport GRPC client certificate
root_cas = "/var/lib/teleport/plugins/slack/auth.cas"   # Teleport cluster CA certs

[slack]
token = "TOKEN_FROM_SLACK"             # Slack Bot OAuth token
# Optional Slack Rooms
recipients = ["team","devops"]

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/slack.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```

(I've swapped out the `auth_server` value from `slack.go-teleport.com:3025` to `0.0.0.0:3025` and `localhost:3025` per https://github.com/gravitational/teleport-plugins/blob/ce39bf750512e4cca043dec352f790019c2bda14/access/slack/config.go#L61 and get the same result.)

After starting my `teleport-slack` plugin: `INFO  Starting Teleport Access Slack Plugin 6.1.1: slack/app.go:72` I get: 

```
"Failed to find roles or traits in x509 identity for access-plugin. Fetching\tfrom backend. If the identity provider allows username changes, this can potentially allow an attacker to change the role of the existing user." services/role.go:933
``` 

And the `start` command appears to hang with no other message:

![Screen Shot 2021-05-04 at 8 18 19 PM](https://user-images.githubusercontent.com/82530006/117087701-e3a39880-ad15-11eb-87a7-b3f9919a96ff.png)

Is there some step I'm missing?  My thanks!

----

Other details:

1. Ran `tctl` command to generate the certs and copied to the correct directory on Linux box per the docs.
2. On AWS EC2 Ubuntu 20.x

**Comment by inertial-frame** [comment]
@marshall-lee - Assigning to you per our chat. Thanks!

**Comment by Joerger** [comment]
@inertial-frame I get the same warning message, but the slackbot still works after these messages are printed for me. Is it the same for you?

**Comment by marshall-lee** [comment]
@inertial-frame it seems like everything is working fine, just try to create an access request and message must appear in the slack.

For troubleshooting, run `teleport-slack` with `-d` option to get an additional logging i.e. `teleport-slack start -d`

**Comment by inertial-frame** [comment]
@Joerger and @marshall-lee - Thanks for looking into this. I've updated our docs to reflect other changes to the install sequence that were described https://github.com/gravitational/teleport-plugins/issues/229 and https://github.com/gravitational/teleport-plugins/pull/228!

I will test this again myself but have two questions (even if it's working correctly, for you):

1. I occasionally get the error:

   ```
   INFO   Starting Teleport Access Slack Plugin 6.1.1: slack/app.go:72
   ERRO   Unable to get Teleport server version slack/app.go:151
   ERRO   Terminating... error:[
   ```

   Instead of the original issue I described. I think this has to do with slightly varied port numbers. What port numbers 
  are required for use with the plugin? I see `3025` per my comments above?

2. In cases where I've been able to move to the next step, I am unable to assign my user a role through `tctl` can you help clarify the steps you've taken?

To be clear, after modifying the installation steps documented in the README and Docs (which don't work when followed as is), I get the issue described above. 

I've tried a couple of different approaches and these result in errors breaking the walkthrough. Being relatively new to the product, I'm assuming that's my fault. Do you mind sharing the ports and exact sequence, you took to complete the article? A photo should take a few seconds to capture.

**Comment by Joerger** [comment]
I ran into those 2 issues too. I used `make access-slack` from the `teleport-plugins` directory, and then ran `teleport-plugins/access/slack/build/teeleport-slack start -c plugin.toml -d`.

To answer your questions:
1. What is the error that is printed after `error:[`? And you need to give the Auth server address, which generally uses port 3025.  
2. None of the default roles have access request permissions. I created the role below with `tctl create -f dev-role.yaml`, created a new user with `tctl users add dev --roles=dev. Then I logged in as dev and made an access request with `tsh request new --roles=admin`.

```yaml
kind: "role"
version: "v3"
metadata:
  name: "dev"
  namespace: "default"
spec:
  allow:
    request:
      roles: ['*']
```

Are you using teleport cloud? I'm actually not sure if the plugin works with Teleport cloud since it doesn't seem to support connecting over ssh, but I'm not certain about this.
