### ISSUE TITLE
Support tokens and other secrets from files for plugins

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport-plugins#246]
LIke the teleport join tokens allow for specifying files with tokens instead of just directly in the files.  
Ex:
```toml
[slack]
token = "xoxb-RdXVfx8Y"             # Slack Bot OAuth token
```
can have the token in a file `/var/lib/teleport-plugins/token.txt`
```toml
[slack]
token = "/var/lib/teleport-plugins/token.txt"             # Slack Bot OAuth token
```

This is also helpful in case the plugin is being run in a container such as a k8s so it can be a secret.
