### ISSUE TITLE
Have slackbot post to a channel for a requested role

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#411]
## Description

Have slack plugin post to a channel mapped to a role requested. Instead of DMs. Folks interested in review of the roles would join channel themselves.

In this case slack plugin does not DM, but posts to a channel with a name of the requested role. If multiple roles are requested, post to all of the channels matching.

Timeline is 1-2 months max. If we can implement it faster.

**Comment by russjones** [comment]
Late March.

**Comment by russjones** [comment]
@xinding33 @klizhentas What is the proposed syntax here?

```toml
[slack]
# Slack Bot OAuth token
token = "xoxb-11xx"

# Optional Slack Rooms
recipients = ["team","devops"]

# Channel map defines a mapping of roles to channel names to send requests to.
[channel_map]

# Send all requests for role to channel "dev-foo" .
"foo"= "dev-foo"

# Wildcard, send any non-matching requests to channel "dev".
"*"= "dev"
```
