### ISSUE TITLE
Allow setting no expiry on `teleport_provision_token` resource

### ISSUE THREAD

**Issue by AClarkie** [gravitational/teleport-plugins#837]
The `teleport_provision_token` resource requires a `metadata.expires` field, however it's now possible to create tokens without an expiry, for example the below yaml can be used:

```
kind: token
version: v2
metadata:
  name: am-token
spec:
  roles: [Bot]

  join_method: iam
```

I've spoken with @zmb3 and @stevenGravy and they believe this is a missing feature potentially following the change [here](https://goteleport.com/docs/changelog/#join-token-api-changes), more context can be found on the below Slack thread
https://goteleport.slack.com/archives/CEZH6UL64/p1685450022714919
