### ISSUE TITLE
mattermost configure does not output all necessary config values

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport-plugins#94]
I ran:

```
$ teleport-mattermost configure > teleport-mattermost.toml
```

This was the output file:
```toml
# example mattermost configuration TOML file
[teleport]
auth-server = "example.com:3025"  # Teleport Auth Server GRPC API address
client-key = "/var/lib/teleport/plugins/mattermost/auth.key" # Teleport GRPC client secret key
client-crt = "/var/lib/teleport/plugins/mattermost/auth.crt" # Teleport GRPC client certificate
root-cas = "/var/lib/teleport/plugins/mattermost/auth.cas"   # Teleport cluster CA certs

[mattermost]
token = "api-token"              # Mattermost Bot OAuth token
secret = "signing-secret-value"  # Mattermost API Signing Secret
channel = "channel-name"         # Mattermost Channel name to post requests to

[http]
listen = ":8081"          # Mattermost interaction callback listener
# https-key-file = "/var/lib/teleport/plugins/mattermost/server.key"  # TLS private key
# https-cert-file = "/var/lib/teleport/plugins/mattermost/server.crt" # TLS certificate

[log]
output = "stderr" # Logger output. Could be "stdout", "stderr" or "/var/lib/teleport/mattermost.log"
severity = "INFO" # Logger severity. Could be "INFO", "ERROR", "DEBUG" or "WARN".
```

When I tried to start, I got this error:
```
$ teleport-mattermost start -c teleport-mattermost.toml
ERRO   Terminating... error:missing required value mattermost.team utils/bail.go:17
```

I added `team` to the `[mattermost]` section and tried again:
```
$ teleport-mattermost start -c teleport-mattermost.toml
ERRO   Terminating... error:missing required value mattermost.url utils/bail.go:17
```

I added `url` to the `[mattermost]` section and tried again:

```
$ teleport-mattermost start -c teleport-mattermost.toml
ERRO   Terminating... error:either http.base-url or http.host is required to be set utils/bail.go:17
```

After adding this value, I was able to start.

`teleport-mattermost configure` should output a proper reference configuration file with all necessary values set.
