### ISSUE TITLE
terraform teleport_role validation issue

### ISSUE THREAD

**Issue by rpuserh** [gravitational/teleport-plugins#980]
Hi,

I'm trying to create role for teleport using terraform

here is my code 

```
locals {
  teleport_roles = {
    k8s-users = yamldecode(file("${path.module}/roles/k8s-user.yaml"))
  }

}

resource "teleport_role" "roles" {
  for_each = local.teleport_roles

  metadata = each.value.metadata
  spec     = each.value.spec
  version  = each.value.version
}

output "k8s-user-spec-debug" {
  value = local.teleport_roles.k8s-users.spec
}
```

here is file `roles/k8s-user.yaml`

```
kind: role
version: v6
metadata:
  name: k8s-users
spec:
  allow:
    kubernetes_groups:
    - system:masters
    kubernetes_labels:
      '*': '*'
    kubernetes_resources:
    - kind: pod
      name: '*'
      namespace: '*'
      verbs:
      - '*'
  deny: {}
  options:
    cert_format: standard
    create_db_user: false
    create_desktop_user: false
    create_host_user: true
    desktop_clipboard: true
    desktop_directory_sharing: true
    enhanced_recording:
    - command
    - network
    forward_agent: false
    idp:
      saml:
        enabled: true
    max_session_ttl: 24h0m0s
    pin_source_ip: false
    port_forwarding: true
    record_session:
      default: best_effort
      desktop: true
    ssh_file_copy: true
```

When I apply/plan I get an error 

```
│ Inappropriate value for attribute "spec": attribute "allow": attribute "kubernetes_labels": element "*": list of string required.
```
Tf validation requires a list of strings for `kubernetes_labels` however it needs to be a map of strings. Also stated in the terraform provider [document](https://goteleport.com/docs/reference/terraform-provider/#specallow-1)
